# Generated by Django 4.2.7 on 2025-06-24 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField()),
                ('diagnosis', models.TextField()),
                ('treatment_notes', models.TextField()),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('vital_signs', models.JSONField(blank=True, null=True)),
                ('medications_prescribed', models.TextField(blank=True, null=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('lab_results', models.TextField(blank=True, null=True)),
                ('imaging_results', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='doctors.doctor')),
            ],
            options={
                'db_table': 'medical_records',
                'ordering': ['-visit_date'],
            },
        ),
    ]
